mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "qyGHtJBZUW"
  database: "web_service"
  max_connections: 16
  timeout: 4

mongo:
  host: "127.0.0.1"
  port: 27017
  auth_db: "admin"
  user:
  password:
  serverSelectionTimeoutMS: 5000

redis:
  address: 'redis://127.0.0.1:6379'
  db: 3
  encoding: "utf-8"
  password:
  maxsize: 16
  timeout: 3

rabbitmq:
  user:
  password:
  host:
  port:
  vhost:

